using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CAUCIWebsiteGeneratoir
{

    using System;


    public class Person
    {
        private String name;
        private String position;
        private String email;
        private String imgLocation = "";
        private String imgHeadLoc = "";
        private String firstName;
        private String lastName;
        private List<QAResponse> qaRespList = new List<QAResponse>();
        private static String QAPath = "C:\\Users\\Chow\\Documents\\Github\\cauciweb\\pages\\board\\test_response.csv";
        private int rank;
         
        //private List<Question> questions = new List<Question>();
        public Person(String name, String position, int rank)
        {
            this.name = name;
            this.position = position;
            this.rank = rank;
            this.email = "test@aol.com";
            this.genQAList();
        }

        public Person(String name, String position, int rank, String email) {
            this.name = name;
            this.position = position;
            this.rank = rank;
            this.email = email;
            this.genQAList();
            if (name != null) {
                String[] names = name.Split(' ');
                this.firstName = names[0];
                this.lastName = names[names.Length - 1];
            }
        }

        private void genQAList()
        {
            //Information retrieval part from the google doc.
            ExcelQAExtractor eQAExtract = new ExcelQAExtractor();
            qaRespList = eQAExtract.getQuestionsFromCSV(QAPath);
        }
        /// <summary>
        /// Generates a div class for name, posiiton and email.
        /// </summary>
        /// <returns>Returns a string containing the name, position and email of the person.</returns>
        public String formatInfo()
        {
            HTMLGenerator htmlGen = new HTMLGenerator();
            String divName = htmlGen.genDivClass("name",
                htmlGen.wrapTag("<h1>", this.getName(), "</h1>"));

            String divPos = htmlGen.genDivClass("position", this.getPosition());

            String divEmail = htmlGen.genDivClass("email", this.getEmail());
            divEmail += "\r\n <br>";
            return (divName + divPos + divEmail);
        }

        public Boolean searchArray<T>(T[] arr, T elem) {
            foreach(T element in arr)
            {
                if (elem.Equals(element))
                    return true;
            }
            return false;
        }

        public String formatQA(String[] ignoreTheseQA)
        {
            HTMLGenerator htmlGen = new HTMLGenerator();

            //Generate the question
          //  int i = 0;
            String buffer = "";
            int qaSize = qaRespList.Count;
            for (int i = 0; i < qaSize; ++i)
             {
            QAResponse curResponse = this.qaRespList.ElementAt(i);
                if (curResponse.getQuestion() == "Theme")
                    curResponse.setAnswer("TBD");
                if (!searchArray<String>(ignoreTheseQA, curResponse.getQuestion()) && (curResponse.getAnswer() != "N/A")) {


                    String divQuest = htmlGen.wrapTag("\r\n<b>\r\n", htmlGen.genDivClass("question", curResponse.getQuestion() + "\r\n"), "</b>");

                    String divAnswer = htmlGen.genDivClass("answer", curResponse.getAnswer() + "\r\n");
                    Console.WriteLine("answer:*" + curResponse.getAnswer() + "*");
                    String breakTag = htmlGen.allignTagWithLastLine("<br>", divAnswer);
                    buffer += divQuest + divAnswer + breakTag;
                }
            }
            return buffer;
        }
       
        /// <summary>
        /// Generates a path string for the image using autogenerated file names.
        /// </summary>
        public void genImageLocation()
        {
            //Figure out a format.
        }
        public void setImgHeadLocation(String imageLocation) {
            imgHeadLoc = imageLocation;
        }
        public void setName(String name)
        {
            this.name = name;
        }

        public void setPosition(String position)
        {
            this.position = position;
        }

        public void setRank(int rank)
        {
            this.rank = rank;
        }

        public String getName()
        {
            return name;
        }

        public String getPosition()
        {
            return position;
        }
        public int getRank()
        {
            return rank;
        }
        public void setQAList(List<QAResponse> qaList) {
            this.qaRespList = qaList;

        }
        public List<QAResponse> getQAList() {
            return qaRespList;
        }


        public void setEmail(String email)
        {
            this.email = email;

        }

        public String getEmail()
        {
            return email;
        }
     
        public String getImgHeadLoc() {
            return imgHeadLoc;
        }

        public String getImageLocation()
        {
            return imgLocation;
        }
        public String getFirstName() {
            return firstName;
        }

       public char getInitialLastName() {
            if (lastName != null)
                return lastName[0];
            else
                return '\0';

        }

        public String getLastName() {
            return lastName;
        }
      
        public void setImageLocation(String imgLocation)
        {
            this.imgLocation = imgLocation;
        }
    }


}
